[profile.default]
src = "contracts"
out = "build/contracts"
libs = ["lib"]
remappings = []
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
localhost = "http://localhost:8545"
testnet = "https://testnet-rpc.quantum-blockchain.io"
mainnet = "https://rpc.quantum-blockchain.io"
