global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Quantum nodes
  - job_name: 'quantum-nodes'
    static_configs:
      - targets: 
        - 'quantum-bootstrap:8545'
        - 'quantum-node-1:8545'
        - 'quantum-node-2:8545'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scheme: http
    params:
      format: ['prometheus']

  # Node exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'quantum-bootstrap:9100'
        - 'quantum-node-1:9100'
        - 'quantum-node-2:9100'
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/status'
    scrape_interval: 15s

  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Sample alerting rules
# rule_files:
#   - "quantum_alerts.yml"