apiVersion: v1
kind: Namespace
metadata:
  name: quantum-blockchain
  labels:
    name: quantum-blockchain
    purpose: production-blockchain
    security-level: high
  annotations:
    kubernetes.io/description: "Production quantum-resistant blockchain network"
    security.policy/encryption: "required"
    security.policy/hsm: "fips-140-2-level-3"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quantum-blockchain-quota
  namespace: quantum-blockchain
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 64Gi
    limits.cpu: "40"
    limits.memory: 128Gi
    persistentvolumeclaims: "30"
    services: "20"
    secrets: "50"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: quantum-blockchain-limits
  namespace: quantum-blockchain
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - default:
      storage: "100Gi"
    type: PersistentVolumeClaim